export const UPDATE_CAR = "UPDATE_PRODUCTS";

export const ADD_TO_ORDER = "ADD_TO_ORDER";
export const ADD_MULTIPLE_TO_ORDER = "ADD_MULTIPLE_TO_ORDER";
export const REMOVE_FROM_ORDER = "REMOVE_FROM_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const UPDATE_ORDER_QUANTITY = "UPDATE_ORDER_QUANTITY";
export const TOGGLE_ORDER = "TOGGLE_ORDER";

